apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.name" . }}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount | default 1}}
  strategy:
    type: {{ .Values.deploymentStrategy | default "RollingUpdate"}}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "service.name" . }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: {{ include "service.name" . }}
        buildNumber: {{ .Values.build.buildNumber | quote }}
      labels:
        app: {{ include "service.name" . }}
    spec:
      serviceAccountName: {{ include "service.name" . }}-sa
      containers:
        - name: {{ include "service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: api
          envFrom:
            - configMapRef:
                name: {{ include "service.name" . }}-config
            - secretRef:
                name: {{ include "service.name" . }}-secret

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}

          readinessProbe:
            httpGet:
              port: api
              path: /actuator/health/readiness
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              port: api
              path: /actuator/health/liveness
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
