apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}-svc
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ include "service.name" . }}
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: api
      appProtocol: http